os: linux
dist: xenial

language: python
python:
  - "3.8"
cache: pip
install:
  - pip install requests
script:
  - python run_tests_travis.py
notifications:
  slack:
    secure: TO+xiUQAIgDqwve0xW5BUnrFq+Ouo/qCaS3QT2q+TdIKe5PTOXr8nGryTuEm2gswypjd8epa8h1D5BLdYCU3D10mhlXE92tZ570Cw5VMAWR/LRmyAOFQeMaGB1GvZgsBAQcshXpApNHyjqVhOMXT0InimFDO/i2PNuxswkb8gyauSbiN6+QG8A9j1efpLkweCSnlPniegFWx93vk5gIbMte2v68xOlzvtxo4e4zRBXifNm70VdY0QxXMLMPsnWToV7ac+irhW+ndD0c0/HPYI1k0PU0LXvhJHP5jd4xmztkM5ilqkPM/912jT8vZ3gNViShDB1WYVFKYaGluG01RqvRdVPOI5Ph2arBYYkfHiULBuJfzkuoI4FFzEckbNCaCIrEOQ2wic3UIbLqR/ZupHo+m/97eMwJfQCYNV6kYsKx7mUpHIQ8XQAUDS7Za82wy7ZwLo9VmdCme9vKj0xcNOFni86uWqItZGuMfjPOF1aPkIu61EuDSbfPSIvGwIfsouFQLbH6pD3Dv424NxSB2QLXdsID/nADgWmasv0+59Pr8QoCdmlif7Ieaj11rOplLLmAmyviwsuoCu3EhYmfy1iiG7ET6G0u8XeRa58RCViN41V9Jo5d41jOWJyNIitNp8ob37no3T1YGOi6/52iiw/0QEv2csjf1z2iXHHgcgcE=
    on_success: always
    on_failure: always
    template:
        - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
        - "Execution time: *%{duration}*"
        - "Message: %{message}"